platform :ios, '7.0'
pod 'AFNetworking', '~> 2.0'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'SimpleAuth', '~> 0.3.9'
pod 'MJExtension', '~> 2.5.2'
pod 'TAPageControl'
pod 'PureLayout'
pod 'JPush-iOS-SDK'
pod 'MMPopupView'
pod 'TPKeyboardAvoiding', '~> 1.2.9'
pod 'DCIntrospect-ARC', '~> 0.0.8'
pod 'FDFullscreenPopGesture', '~> 1.1'
pod 'SDWebImage', '~> 3.7.3'
pod 'SocketRocket', '~> 0.4.2'
pod 'PAPreferences', '~> 0.5'
pod 'Google/SignIn', '~> 1.2.1'
pod 'Fabric'
pod 'TwitterCore', '~> 1.9.0'
pod 'TwitterKit', '~> 1.9.0'
pod 'FMDB', '~> 2.5'
pod 'LKDBHelper', '~> 2.1.6'
pod 'MJRefresh', '~> 3.0.5'

